backend:
  name: github
  repo: lflogistica18-lang/ProyectoChat_APA
  branch: main

local_backend:
  url: "http://localhost:8081/api/v1"

media_folder: "Imagenes"
public_folder: "Imagenes"

collections:
  - name: "landing"
    label: "Landing Page"
    files:
      - label: "Contenido Principal"
        name: "content"
        file: "data/landing.json"
        fields:
          - { label: "Hero Section", name: "hero", widget: "object", fields: [
              { label: "Ubicacion", name: "etiqueta_ubicacion", widget: "string" },
              { label: "Titulo Regular", name: "titulo_regular", widget: "string" },
              { label: "Titulo Destacado", name: "titulo_destacado", widget: "string" },
              { label: "Descripcion", name: "descripcion", widget: "text" }
            ]}
          - { label: "Menu de Viandas", name: "menu", widget: "list", fields: [
              { label: "Titulo del Plato", name: "titulo", widget: "string" },
              { label: "Descripcion", name: "descripcion", widget: "text" },
              { label: "Precio", name: "precio", widget: "string" },
              { label: "Imagen", name: "imagen", widget: "image" },
              { label: "Categoria", name: "etiqueta", widget: "string" },
              { label: "Color de Etiqueta", name: "etiqueta_color", widget: "select", options: [
                  { label: "Naranja", value: "bg-primary-container text-on-primary-container" },
                  { label: "Verde", value: "bg-tertiary-container text-on-tertiary-container" }
                ]},
              { label: "Calorias", name: "calorias", widget: "string" },
              { label: "Proteinas", name: "proteinas", widget: "string" }
            ]}
